### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by bitchecker** [Clivern/Lynx#141]
**Describe the bug**
Hi,
I'm trying to run the application on a native server (Fedora 41) starting from your documentation Ubuntu based.

I'm getting an error when I run `make migrate` because it seems that the `.env.local` file that I created is not considered, and it tries to reach the database on localhost, but the database is on another server.

The errors that I get are:
```
>> ============= Create database ============= <<

16:54:41.733 [error] Postgrex.Protocol (#PID<0.226.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused

16:54:41.736 [error] :gen_statem #PID<0.226.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.6.0) lib/db_connection/connection.ex:122: DBConnection.Connection.handle_event/4
    (stdlib 5.2.3.3) gen_statem.erl:1397: :gen_statem.loop_state_callback/11
    (stdlib 5.2.3.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Queue: [internal: {:connect, :init}]
Postponed: []
State: Postgrex.Protocol
Callback mode: :handle_event_function, state_enter: false

16:54:41.739 [error] Postgrex.Protocol (#PID<0.232.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused

16:54:41.739 [error] :gen_statem #PID<0.232.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.6.0) lib/db_connection/connection.ex:122: DBConnection.Connection.handle_event/4
    (stdlib 5.2.3.3) gen_statem.erl:1397: :gen_statem.loop_state_callback/11
    (stdlib 5.2.3.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Queue: [internal: {:connect, :init}]
Postponed: []
State: Postgrex.Protocol
Callback mode: :handle_event_function, state_enter: false
** (Mix) The database for Lynx.Repo couldn't be created: killed
make: *** [Makefile:68: migrate] Error 1
```

**Development or production environment**
 - OS: `Fedora 41`

**Comment by Clivern** [comment]
Hi @bitchecker,

Can you do something like the following before doing the db migration? I think i forgot to add a step in the docs to load `.env.local` as environment variables.

```zsh
$ export $(cat .env.local | xargs)
$ make deps
$ make migrate
```

**Comment by bitchecker** [comment]
Loading the environmental file, it works! 😃 

That step is not present at the moment on the installation section. Thanks @Clivern.
