### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by bitchecker** [Clivern/Lynx#143]
**Describe the bug**
After the local installation (no docker environment) and first login, if I click to `Profile Settings -> Profile` I get an `Internal Server Error` with the following entries in logs:
```
mix[34337]: [error] #PID<0.766.0> running LynxWeb.Endpoint (connection #PID<0.765.0>, stream id 1) terminated
mix[34337]: Server: X.X.X.X:80 (http)
mix[34337]: Request: GET /admin/profile
mix[34337]: ** (exit) an exception was raised:
mix[34337]:     ** (Postgrex.Error) ERRORE 26000 (invalid_sql_statement_name) l'istruzione preparata "ecto_626" non esiste
mix[34337]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
mix[34337]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
mix[34337]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
mix[34337]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
mix[34337]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
mix[34337]:         (lynx 0.12.4) lib/lynx/module/settings_module.ex:32: Lynx.Module.SettingsModule.get_config/2
mix[34337]:         (lynx 0.12.4) lib/lynx_web/controllers/page_controller.ex:160: LynxWeb.PageController.profile/2
mix[34337]:         (lynx 0.12.4) lib/lynx_web/controllers/page_controller.ex:5: LynxWeb.PageController.action/2
```

After restart also if I click on the logo (for go to homepage) I get the same error:
```
mix[53111]: [error] #PID<0.600.0> running LynxWeb.Endpoint (connection #PID<0.599.0>, stream id 1) terminated
mix[53111]: Server: X.X.X.X:80 (http)
mix[53111]: Request: GET /admin/projects
mix[53111]: ** (exit) an exception was raised:
mix[53111]:     ** (Postgrex.Error) ERRORE 26000 (invalid_sql_statement_name) l'istruzione preparata "ecto_658" non esiste
mix[53111]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
mix[53111]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
mix[53111]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
mix[53111]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
mix[53111]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
mix[53111]:         (lynx 0.12.4) lib/lynx/module/user_module.ex:18: Lynx.Module.UserModule.get_user_by_id/1
mix[53111]:         (lynx 0.12.4) lib/lynx/middleware/ui_auth.ex:65: Lynx.Middleware.UIAuthMiddleware.call/2
mix[53111]:         (lynx 0.12.4) LynxWeb.Router.browser/2
```

**Additional context**
Only a service restart can solve the error, but if you click again, the error happens again.

**Comment by bitchecker** [comment]
After restart also if I click on the logo (for go to homepage) I get the same error:
```
mix[53111]: [error] #PID<0.600.0> running LynxWeb.Endpoint (connection #PID<0.599.0>, stream id 1) terminated
mix[53111]: Server: X.X.X.X:80 (http)
mix[53111]: Request: GET /admin/projects
mix[53111]: ** (exit) an exception was raised:
mix[53111]:     ** (Postgrex.Error) ERRORE 26000 (invalid_sql_statement_name) l'istruzione preparata "ecto_658" non esiste
mix[53111]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
mix[53111]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
mix[53111]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
mix[53111]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
mix[53111]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
mix[53111]:         (lynx 0.12.4) lib/lynx/module/user_module.ex:18: Lynx.Module.UserModule.get_user_by_id/1
mix[53111]:         (lynx 0.12.4) lib/lynx/middleware/ui_auth.ex:65: Lynx.Middleware.UIAuthMiddleware.call/2
mix[53111]:         (lynx 0.12.4) LynxWeb.Router.browser/2
```

**Comment by bitchecker** [comment]
ok I think that I understood the issue:
In the `Installation page` when you're going to setup for the first time the application, at the `application url` entry, I setup the "external ip" that is the ip of the server (the app is configured to run on localhost but nginx act as reverse proxy).

Reinitializing the app using `http://localhost:4000` seems working properly at the moment.

**Comment by Clivern** [comment]
Hi @bitchecker, Can you provide more info regarding the postgresql database server and version? it sound to me like some feature is missing in database.

**Comment by Clivern** [comment]
I think this might be related https://github.com/elixir-ecto/postgrex/issues/468.

**Comment by bitchecker** [comment]
> Hi @bitchecker, Can you provide more info regarding the postgresql database server and version? it sound to me like some feature is missing in database.

It's a postgres server, release 16.

**Comment by Clivern** [comment]
That makes sense now because pgbouncer doesn't support prepared statements. Can you try to run from the following new branch & let me know if it works. I can release it if it causes no issues to postgresql without pgbouncer setups. 

```bash
$ git clone -b fix/issue-143 https://github.com/Clivern/Lynx.git
```

**Comment by bitchecker** [comment]
Now I'm not able to log in too:
```
mix[23678]: [error] #PID<0.653.0> running LynxWeb.Endpoint (connection #PID<0.652.0>, stream id 1) terminated
mix[23678]: Server: 10.0.0.95:80 (http)
mix[23678]: Request: GET /login
mix[23678]: ** (exit) an exception was raised:
mix[23678]:     ** (Postgrex.Error) ERRORE 26000 (invalid_sql_statement_name) l'istruzione preparata "ecto_435" non esiste
mix[23678]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
mix[23678]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
mix[23678]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
mix[23678]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
mix[23678]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
mix[23678]:         (lynx 0.12.4) lib/lynx/module/install_module.ex:18: Lynx.Module.InstallModule.is_installed/0
mix[23678]:         (lynx 0.12.4) lib/lynx_web/controllers/page_controller.ex:21: LynxWeb.PageController.login/2
mix[23678]:         (lynx 0.12.4) lib/lynx_web/controllers/page_controller.ex:5: LynxWeb.PageController.action/2
```

**Comment by Clivern** [comment]
Strange that i have a PgBouncer v1.23.1, PostgreSQL v16.6 & Ubuntu 24 and it works fine. I see they added the support https://github.com/pgbouncer/pgbouncer/discussions/973 from v1.21.0

**Comment by bitchecker** [comment]
Really, I recreated entirely the stack from zero.

I'm going to rebuild it again and let you know.

**Comment by bitchecker** [comment]
On installing the application, I get the same error:
```
mix[22444]: request_id=GBOfVNdQp9vXQOIAAAKh [info] Incoming POST Request to /action/install? and body %{"admin_email" => "admin@domain.ltd", "admin_name" => "admin", "admin_password" => "REDACTED", "app_email" => "admin@domain.ltd", "app_name" => "Lynx", "app_url" => "http://X.X.X.X/"}
mix[22444]: request_id=GBOfVNdQp9vXQOIAAAKh [info] Sent 500 in 1ms
mix[22444]: [error] #PID<0.561.0> running LynxWeb.Endpoint (connection #PID<0.560.0>, stream id 1) terminated
mix[22444]: Server: X.X.X.X:80 (http)
mix[22444]: Request: POST /action/install
mix[22444]: ** (exit) an exception was raised:
mix[22444]:     ** (Postgrex.Error) ERRORE 26000 (invalid_sql_statement_name) l'istruzione preparata "ecto_658" non esiste
mix[22444]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
mix[22444]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
mix[22444]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
mix[22444]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
mix[22444]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
mix[22444]:         (lynx 0.12.4) lib/lynx/module/install_module.ex:18: Lynx.Module.InstallModule.is_installed/0
mix[22444]:         (lynx 0.12.4) lib/lynx_web/controllers/misc_controller.ex:27: LynxWeb.MiscController.install/2
mix[22444]:         (lynx 0.12.4) lib/lynx_web/controllers/misc_controller.ex:5: LynxWeb.MiscController.action/2
```

I restarted the app, and I was able to finish the installation. The error always seems the same.

After the installation, I log in into the application, and I was trying to do something, but I get again the classic `Internal Server Error` with this in logs:
```
mix[22814]: [error] #PID<0.536.0> running LynxWeb.Endpoint (connection #PID<0.535.0>, stream id 1) terminated
mix[22814]: Server: X.X.X.X:80 (http)
mix[22814]: Request: GET /
mix[22814]: ** (exit) an exception was raised:
mix[22814]:     ** (Postgrex.Error) ERRORE 26000 (invalid_sql_statement_name) l'istruzione preparata "ecto_50" non esiste
mix[22814]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
mix[22814]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
mix[22814]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
mix[22814]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
mix[22814]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
mix[22814]:         (lynx 0.12.4) lib/lynx/module/install_module.ex:18: Lynx.Module.InstallModule.is_installed/0
mix[22814]:         (lynx 0.12.4) lib/lynx_web/controllers/page_controller.ex:85: LynxWeb.PageController.home/2
mix[22814]:         (lynx 0.12.4) lib/lynx_web/controllers/page_controller.ex:5: LynxWeb.PageController.action/2
```

I restarted the app again, and I tried to create a team, on the right I was able to see that the team was successfully created but here we go again with:
```
mix[22869]: [error] #PID<0.666.0> running LynxWeb.Endpoint (connection #PID<0.665.0>, stream id 1) terminated
mix[22869]: Server: X.X.X.X:80 (http)
mix[22869]: Request: GET /admin/teams
mix[22869]: ** (exit) an exception was raised:
mix[22869]:     ** (Postgrex.Error) ERRORE 26000 (invalid_sql_statement_name) l'istruzione preparata "ecto_402" non esiste
mix[22869]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
mix[22869]:         (ecto_sql 3.11.2) lib/ecto/adapters/sql.ex:952: Ecto.Adapters.SQL.execute/6
mix[22869]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
mix[22869]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
mix[22869]:         (ecto 3.11.2) lib/ecto/repo/queryable.ex:154: Ecto.Repo.Queryable.one/3
mix[22869]:         (lynx 0.12.4) lib/lynx/service/auth_service.ex:72: Lynx.Service.AuthService.is_authenticated/2
mix[22869]:         (lynx 0.12.4) lib/lynx/middleware/ui_auth.ex:47: Lynx.Middleware.UIAuthMiddleware.call/2
mix[22869]:         (lynx 0.12.4) LynxWeb.Router.browser/2
```

Another strange behaviour is that every time that I restart the application, I don't need to log in into the app, but I'm already in...cookies and whatever should be cleaned at server restart, right?

**Comment by bitchecker** [comment]
I think that I got the issue!

I don't understand if with your branch, you disabled prepared statement or whatever, but for sure, pgbouncer was completely ignoring them (default behaviour).

Furthermore, I can also see that password are now masked with "`REDACTED`" string.

**Comment by bitchecker** [comment]
> In fact, users shouldn't lose access during a server restart since they expect a seamless experience even during such events; losing access could lead to frustration for them. Lynx can operate behind a load balancer because it uses database sessions by default, so if one node goes down for any reason, user requests will be redirected to another node without interruption.

Oh ok, this is great! Thanks for clarification!

> This change https://github.com/Clivern/Lynx/blob/fix/issue-143/lib/lynx/repo.ex#L9 shall solve the issue with named mysql statements for pgbouncer so if this branch works fine for you, please let me know!

At this point, I really should check to deploy server from master branch and see if it works too or not. As I said, pgbouncer, by default, is not configured to work with them, and now I updated the config (is the first time that I get this issue).

**Comment by bitchecker** [comment]
@Clivern,
I can confirm that it works with both branches now.

Maybe the new one seems a little bit faster but I don't have numbers from a good test case.

**Comment by Clivern** [comment]
That's great to hear! i will be doing a few check, merge it to the master
branch and release a new version. Thanks!

**Comment by Clivern** [comment]
The patch is released, please feel free to open a new issue if you face the issue again.
